import Head from 'next/head';
import SingleRow from '../Components/Common/SingleRow/SingleRow';
import ReverseSingleRow from '../Components/Common/SingleRow/ReverseSingleRow';
import Carousel from '../Components/Common/ContactCarousel/Carousel';
import Service from '../Components/Common/ServicesSection/Service';
import EcoSystem from '../Components/Common/EcoSystem/EcoSystem';
import Testimonial from '../Components/Common/Testimonial/Testimonial';
import Explore from '../Components/Common/Explore/Explore';
import News from '../Components/Common/NewsAndEvents/News';
import 'swiper/css/bundle';
import { FiHeadphones } from 'react-icons/fi';
import { GoLocation } from 'react-icons/go';
import { GiAlarmClock } from 'react-icons/gi';
import { BiCog } from 'react-icons/bi';
import { BsBagFill, BsStack } from 'react-icons/bs';
import { IoBookSharp } from 'react-icons/io5';
export default function Home() {
	return (
		<div className='container mx-auto lg:container lg:mx-auto lg:container lg:px-36 font-Inter'>
			<Head>
				<title>
					SkyLine | Top cloud consultant in Nagpur | Salesforce
					partner
				</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<SingleRow />
			<ReverseSingleRow />
			<Carousel />
			{/* Service Section Start */}
			<div className='service px-4 '>
				<h3 className='text-center text-3xl text-blue-500 font-medium lg:font-bold lg:text-5xl'>
					Services
				</h3>
				<p className='px-4 mt-4 text-center font-normal text-gray-400 text-xl'>
					Our services offering will carter to all your business
					automation requirements and give you customized digital
					solutions
				</p>
				<p className='px-4 mt-4 text-center font-normal text-gray-400 text-xl'>
					Because we simply want to make what you want and help you
					thrive!
				</p>
				<div className='grid gap-4 grid-cols-1 lg:grid-cols-4'>
					<Service
						icon={<GoLocation />}
						head='Cloud: Professional and Managed Services'
					/>
					<Service
						icon={<FiHeadphones />}
						head='Technology Consulting & Customer Experience'
					/>
					<Service
						icon={<GiAlarmClock />}
						head='Product Engineering Services'
					/>
					<Service icon={<BiCog />} head='Digital Transformation' />
					<Service
						icon={<BsBagFill />}
						head='Business Automation & Change Management	'
					/>
					<Service
						icon={<BsStack />}
						head='Application Integration Services'
					/>
					<div className=''>
						<Service
							icon={<IoBookSharp />}
							head='Data & Predictive Analytics '
						/>
					</div>
					<div className=''>
						<Service
							icon={<BiCog />}
							head='Digital Transformation'
						/>
					</div>
				</div>
			</div>

			<EcoSystem />
			<Testimonial />
			<Explore />
			<News />
		</div>
	);
}
